"""Synthetic lens generators: everything lens/*.py's round-trip tests check
their fits against. Every generator funnels its final flux map through
``synth.sensor.frame`` (extending the foundation module by calling it, not
copying its noise model), matching ``synth/sensor.py``'s own house-rule-4
convention: a known ground truth in, the same numbers recovered by the real
analysis code, out.
"""

from __future__ import annotations

import cv2
import numpy as np
from scipy import ndimage
from scipy.special import erf

from calsuite.lens import flats as flatsmod
from calsuite.lens.charuco import _plane_offsets
from calsuite.raw import RawFrame
from calsuite.synth import sensor as synth_sensor


def project_board_corners(board, K: np.ndarray, dist_coeffs: np.ndarray, rvec: np.ndarray, tvec: np.ndarray):
    """Ground-truth pinhole + Brown-Conrady projection of every board
    corner -- the "known camera" half of distortion.py's/tca.py's fit
    round trips, without needing to render and re-detect a pixel image
    (the detector's own noise is charuco.py's concern, tested separately).
    Returns ``(objp (N,3), imgp (N,2))``."""
    objp = board.getChessboardCorners().astype(np.float64)
    imgp, _ = cv2.projectPoints(objp, rvec, tvec, K, dist_coeffs)
    return objp, imgp.reshape(-1, 2)


def synthetic_views(
    board,
    K: np.ndarray,
    dist_coeffs: np.ndarray,
    image_size: tuple,
    n_views: int,
    rng: np.random.Generator,
    *,
    coverage: str = "full",
    min_corners: int = 8,
):
    """``n_views`` synthetic ``distortion.BoardView`` correspondences,
    generated by rejection sampling over random board poses until each one
    lands enough corners inside the frame. ``coverage="full"`` (the
    default) samples poses that fill most of the frame, including the
    field's outer edge -- realistic coverage. ``coverage="center"`` keeps
    the board small and centered, the synthetic input the coverage-refusal
    test needs (a dataset that genuinely never touches the outer field)."""
    from calsuite.lens.distortion import BoardView

    width, height = image_size
    objp = board.getChessboardCorners().astype(np.float64)
    board_w_mm = float(objp[:, 0].max() - objp[:, 0].min())
    fx = float(K[0, 0])
    views = []
    attempts = 0
    while len(views) < n_views and attempts < n_views * 200:
        attempts += 1
        frac = rng.uniform(0.12, 0.30) if coverage == "center" else rng.uniform(0.35, 0.95)
        z = fx * board_w_mm / (frac * width)
        tx = rng.uniform(-0.12, 0.12) * z * width / fx
        ty = rng.uniform(-0.12, 0.12) * z * height / fx
        tvec = np.array([tx, ty, z])
        max_tilt = 0.08 if coverage == "center" else 0.3
        rvec = rng.normal(0.0, max_tilt, size=3)
        imgp, _ = cv2.projectPoints(objp, rvec, tvec, K, dist_coeffs)
        imgp = imgp.reshape(-1, 2)
        inside = (imgp[:, 0] >= 0) & (imgp[:, 0] < width) & (imgp[:, 1] >= 0) & (imgp[:, 1] < height)
        if inside.sum() < min_corners:
            continue
        ids = np.where(inside)[0].astype(np.int32)
        views.append(BoardView(corners=imgp[inside].astype(np.float64), ids=ids, name=f"view{len(views)}"))
    return views


def render_board_frame(
    model: synth_sensor.SensorModel,
    board_img8: np.ndarray,
    mm_per_px: float,
    K: np.ndarray,
    dist_coeffs: np.ndarray,
    rvec: np.ndarray,
    tvec: np.ndarray,
    *,
    tca_scale: tuple = (1.0, 1.0),
    black_flux_e_per_s: float = 2.0e3,
    white_flux_e_per_s: float = 4.0e4,
    exposure_s: float = 0.02,
    rng: np.random.Generator,
) -> RawFrame:
    """Render ``board_img8`` (as returned by ``lens.charuco.render_board_image``)
    through a pinhole + Brown-Conrady camera into a synthetic Bayer
    ``RawFrame``, by inverse-warping: for every sensor pixel, undo the
    (per-channel-scaled, for TCA) distortion to get an undistorted camera
    ray, intersect it with the board's z=0 plane, and sample the board
    texture there. ``tca_scale = (r_scale, b_scale)`` emulates lateral
    chromatic aberration as a radial scale of the *normalized* ray before
    intersection -- the same "scale about the optical axis" TCA
    lens/tca.py fits for, just applied in the forward/render direction.
    """
    rows, cols = model.shape
    bh, bw = board_img8.shape
    R, _ = cv2.Rodrigues(np.asarray(rvec, dtype=np.float64))
    Rt = R.T
    cam_center = (-Rt @ np.asarray(tvec, dtype=np.float64).reshape(3, 1)).reshape(3)

    yy, xx = np.mgrid[0:rows, 0:cols]
    pix = np.stack([xx.ravel(), yy.ravel()], axis=1).astype(np.float64)

    def channel_texture(scale: float) -> np.ndarray:
        norm = cv2.undistortPoints(pix.reshape(-1, 1, 2), K, dist_coeffs).reshape(-1, 2)
        norm = norm / scale
        rays_cam = np.concatenate([norm, np.ones((norm.shape[0], 1))], axis=1)
        rays_world = rays_cam @ Rt.T
        with np.errstate(divide="ignore", invalid="ignore"):
            s = -cam_center[2] / rays_world[:, 2]
        X = cam_center[0] + s * rays_world[:, 0]
        Y = cam_center[1] + s * rays_world[:, 1]
        bx = X / mm_per_px
        by = Y / mm_per_px
        valid = np.isfinite(bx) & np.isfinite(by) & (bx >= 0) & (bx < bw - 1) & (by >= 0) & (by < bh - 1)
        sampled = ndimage.map_coordinates(
            board_img8.astype(np.float64), [np.clip(by, 0, bh - 1), np.clip(bx, 0, bw - 1)], order=1, mode="nearest"
        )
        out = np.full(pix.shape[0], 255.0)  # off the board -> bright, matching the target's white surround
        out[valid] = sampled[valid]
        return out.reshape(rows, cols)

    r_scale, b_scale = tca_scale
    r_tex = channel_texture(r_scale)
    g_tex = channel_texture(1.0)
    b_tex = channel_texture(b_scale)

    flux = np.full((rows, cols), white_flux_e_per_s)
    # Assemble a single physical flux map with each pixel's own CFA channel's
    # texture baked in -- a real photosite only ever sees one filtered
    # channel, matching raw.planes()'s phase convention (see charuco.py).
    # tex is the board's own 8-bit render, 255 = white paper/quiet zone,
    # 0 = a black marker/chessboard module, so it maps linearly onto
    # [black_flux_e_per_s, white_flux_e_per_s] the same way, polarity
    # preserved -- an inverted image would decode ArUco bits wrong.
    offsets = _plane_offsets(model.pattern)
    for name, tex in (("R", r_tex), ("G1", g_tex), ("G2", g_tex), ("B", b_tex)):
        dr, dc = offsets[name]
        flux[dr::2, dc::2] = black_flux_e_per_s + (white_flux_e_per_s - black_flux_e_per_s) * (
            tex[dr::2, dc::2] / 255.0
        )

    return synth_sensor.frame(model, exposure_s, flux, temp_c=20.0, rng=rng)


def render_flat_pose(
    model: synth_sensor.SensorModel,
    v_coeffs: list,
    s_coeffs: list,
    pose: flatsmod.Pose,
    *,
    base_flux_e_per_s: float = 3.0e4,
    exposure_s: float = 0.05,
    rng: np.random.Generator,
) -> RawFrame:
    """A flat-field frame with known vignetting (``v_coeffs``) and known
    source non-uniformity (``s_coeffs``) as seen through ``pose`` -- the
    ground truth ``lens.flats.self_calibrate_flat`` is checked against.
    Reuses ``lens.flats``'s own coordinate/pose functions so the synthetic
    generator and the solver share one definition of what a pose does."""
    shape = model.shape
    yy, xx = np.mgrid[0 : shape[0], 0 : shape[1]]
    xn, yn = flatsmod.normalize_coords(xx, yy, shape)
    r2 = xn * xn + yn * yn
    v2, v4 = v_coeffs
    v_map = np.exp(v2 * r2 + v4 * r2 * r2)
    u, v = flatsmod.pose_transform(xn, yn, pose)
    s0, su, sv, suu, suv, svv = s_coeffs
    s_map = np.exp(s0 + su * u + sv * v + suu * u * u + suv * u * v + svv * v * v)
    flux = base_flux_e_per_s * v_map * s_map
    return synth_sensor.frame(model, exposure_s, flux, temp_c=20.0, rng=rng)


def render_slanted_edge(
    model: synth_sensor.SensorModel,
    angle_deg: float,
    sigma_px: float,
    *,
    low_flux_e_per_s: float = 2.0e3,
    high_flux_e_per_s: float = 4.0e4,
    exposure_s: float = 0.02,
    rng: np.random.Generator,
) -> RawFrame:
    """A slanted-edge target with an *exact* Gaussian-blurred step (the
    error function is the exact convolution of a step with a Gaussian, so
    this is the analytic ground truth mtf.py's e-SFR is checked against:
    MTF(f) = exp(-2 pi^2 sigma^2 f^2)). ``angle_deg`` is measured from
    vertical, matching mtf.py's own convention (0 degrees = a perfectly
    vertical edge; per-row column shift = tan(angle_deg))."""
    rows, cols = model.shape
    yy, xx = np.mgrid[0:rows, 0:cols].astype(np.float64)
    cx, cy = (cols - 1) / 2.0, (rows - 1) / 2.0
    theta = np.radians(angle_deg)
    nx, ny = np.cos(theta), -np.sin(theta)
    d = (xx - cx) * nx + (yy - cy) * ny
    frac = 0.5 * (1.0 + erf(d / (sigma_px * np.sqrt(2.0))))
    flux = low_flux_e_per_s + (high_flux_e_per_s - low_flux_e_per_s) * frac
    return synth_sensor.frame(model, exposure_s, flux, temp_c=20.0, rng=rng)


def render_stars(
    model: synth_sensor.SensorModel,
    stars: list,
    *,
    background_flux_e_per_s: float = 50.0,
    exposure_s: float = 1.0,
    rng: np.random.Generator,
) -> RawFrame:
    """``stars``: a list of dicts ``{"x","y","amplitude","sigma_major",
    "sigma_minor","theta_deg"}`` (sensor px, e-/s peak amplitude, radians
    theta is the major axis's angle from the sensor x-axis) -- summed
    elliptical Gaussians, the ground truth psf.py's moment/ellipticity/
    orientation recovery is checked against."""
    rows, cols = model.shape
    yy, xx = np.mgrid[0:rows, 0:cols].astype(np.float64)
    flux = np.full((rows, cols), background_flux_e_per_s)
    for star in stars:
        theta = np.radians(star["theta_deg"])
        dx, dy = xx - star["x"], yy - star["y"]
        ca, sa = np.cos(theta), np.sin(theta)
        major = ca * dx + sa * dy
        minor = -sa * dx + ca * dy
        flux = flux + star["amplitude"] * np.exp(
            -0.5 * ((major / star["sigma_major"]) ** 2 + (minor / star["sigma_minor"]) ** 2)
        )
    return synth_sensor.frame(model, exposure_s, flux, temp_c=20.0, rng=rng)
